obj-y	+= scmi_agent-uclass.o
obj-y	+= smt.o
obj-$(CONFIG_ARM_SMCCC)		+= smccc_agent.o
obj-$(CONFIG_DM_MAILBOX)	+= mailbox_agent.o
obj-$(CONFIG_SANDBOX)		+= sandbox-scmi_agent.o sandbox-scmi_devices.o
obj-$(CONFIG_SCMI_BASE)		+= scmi_base.o
obj-$(CONFIG_SCMI_HAILO)	+= scmi_hailo.o
