// SPDX-License-Identifier: GPL-2.0
/*
 * Copyright (c) 2019-2023 Hailo Technologies Ltd. All rights reserved. 
 */
 
#ifndef _PINCTRL_HAILO15_PROPERTIES_H
#define _PINCTRL_HAILO15_PROPERTIES_H

#include "pinctrl-hailo15.h"

static const struct pinctrl_pin_desc hailo15_pins[] = {
    PINCTRL_PIN(0, "GPIO_0"),
    PINCTRL_PIN(1, "GPIO_1"),
    PINCTRL_PIN(2, "GPIO_2"),
    PINCTRL_PIN(3, "GPIO_3"),
    PINCTRL_PIN(4, "GPIO_4"),
    PINCTRL_PIN(5, "GPIO_5"),
    PINCTRL_PIN(6, "GPIO_6"),
    PINCTRL_PIN(7, "GPIO_7"),
    PINCTRL_PIN(8, "GPIO_8"),
    PINCTRL_PIN(9, "GPIO_9"),
    PINCTRL_PIN(10, "GPIO_10"),
    PINCTRL_PIN(11, "GPIO_11"),
    PINCTRL_PIN(12, "GPIO_12"),
    PINCTRL_PIN(13, "GPIO_13"),
    PINCTRL_PIN(14, "GPIO_14"),
    PINCTRL_PIN(15, "GPIO_15"),
    PINCTRL_PIN(16, "GPIO_16"),
    PINCTRL_PIN(17, "GPIO_17"),
    PINCTRL_PIN(18, "GPIO_18"),
    PINCTRL_PIN(19, "GPIO_19"),
    PINCTRL_PIN(20, "GPIO_20"),
    PINCTRL_PIN(21, "GPIO_21"),
    PINCTRL_PIN(22, "GPIO_22"),
    PINCTRL_PIN(23, "GPIO_23"),
    PINCTRL_PIN(24, "GPIO_24"),
    PINCTRL_PIN(25, "GPIO_25"),
    PINCTRL_PIN(26, "GPIO_26"),
    PINCTRL_PIN(27, "GPIO_27"),
    PINCTRL_PIN(28, "GPIO_28"),
    PINCTRL_PIN(29, "GPIO_29"),
    PINCTRL_PIN(30, "GPIO_30"),
    PINCTRL_PIN(31, "GPIO_31"),
    PINCTRL_PIN(32, "uart0_txd"),
    PINCTRL_PIN(33, "uart0_rxd"),
    PINCTRL_PIN(34, "uart1_txd"),
    PINCTRL_PIN(35, "uart1_rxd"),
    PINCTRL_PIN(36, "eth_rgmii_tx_clk"),
    PINCTRL_PIN(37, "eth_rgmii_tx_ctl"),
    PINCTRL_PIN(38, "eth_rgmii_txd_0"),
    PINCTRL_PIN(39, "eth_rgmii_txd_1"),
    PINCTRL_PIN(40, "eth_rgmii_txd_2"),
    PINCTRL_PIN(41, "eth_rgmii_txd_3"),
    PINCTRL_PIN(42, "eth_rgmii_rxd_0"),
    PINCTRL_PIN(43, "eth_rgmii_rxd_1"),
    PINCTRL_PIN(44, "eth_rgmii_rxd_2"),
    PINCTRL_PIN(45, "eth_rgmii_rxd_3"),
    PINCTRL_PIN(46, "eth_rgmii_rx_clk"),
    PINCTRL_PIN(47, "eth_rgmii_rx_ctl"),
    PINCTRL_PIN(48, "eth_mdc"),
    PINCTRL_PIN(49, "eth_mdio"),
    PINCTRL_PIN(50, "i2c0_sda"),
    PINCTRL_PIN(51, "i2c0_scl"),
    PINCTRL_PIN(52, "i2c1_sda"),
    PINCTRL_PIN(53, "i2c1_scl"),
    PINCTRL_PIN(54, "jtag_tdi"),
    PINCTRL_PIN(55, "jtag_tdo"),
    PINCTRL_PIN(56, "jtag_tms"),
    PINCTRL_PIN(57, "jtag_tck"),
    PINCTRL_PIN(58, "jtag_trstn"),
    PINCTRL_PIN(59, "flash_sclk"),
    PINCTRL_PIN(60, "flash_cs_0"),
    PINCTRL_PIN(61, "flash_cs_1"),
    PINCTRL_PIN(62, "flash_reset"),
    PINCTRL_PIN(63, "flash_dq_0"),
    PINCTRL_PIN(64, "flash_dq_1"),
    PINCTRL_PIN(65, "flash_dq_2"),
    PINCTRL_PIN(66, "flash_dq_3"),
    PINCTRL_PIN(67, "i2s_sck"),
    PINCTRL_PIN(68, "i2s_ws"),
    PINCTRL_PIN(69, "i2s_sdo"),
    PINCTRL_PIN(70, "i2s_sdi"),
    PINCTRL_PIN(71, "pcie_clkreq"),
    PINCTRL_PIN(72, "pcie_wake"),
    PINCTRL_PIN(73, "safety_error"),
    PINCTRL_PIN(74, "safety_fatal"),
    PINCTRL_PIN(75, "parallel_pclk"),
};

#endif /* _PINCTRL_HAILO15_PROPERTIES_H */